name: Create Releases and Build Docker images

on:
  push:
    branches:
      - 'master'

jobs:
  create-release-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load .env file
        run: |
          set -a
          source .env
          set +a
          echo "APACHE_VERSION=$APACHE_VERSION" >> $GITHUB_ENV
          echo "APACHE_VERSION_MAJOR=$APACHE_VERSION_MAJOR" >> $GITHUB_ENV
          echo "ALPINE_VERSION=$ALPINE_VERSION" >> $GITHUB_ENV

      - name: Debug print
        run: |
          echo "APACHE_VERSION=$APACHE_VERSION"
          echo "APACHE_VERSION_MAJOR=$APACHE_VERSION_MAJOR"
          echo "ALPINE_VERSION=$ALPINE_VERSION"

      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Releases
        run: |
          TAG_NAME="httpd-${APACHE_VERSION}"
          DOCKER_HUB_LINK="https://hub.docker.com/layers/mxmd/httpd/${APACHE_VERSION}-alpine${ALPINE_VERSION}/"
          if ! gh release view $TAG_NAME > /dev/null 2>&1; then
            # Create GH Release if it does not exist
            gh release create $TAG_NAME \
              --title "Apache ${APACHE_VERSION} release" \
              --notes "Release of Docker image for Apache ${APACHE_VERSION}. [View on Docker Hub]($DOCKER_HUB_LINK)"
            echo "RELEASE_CREATED=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            mxmd/httpd:${{ env.APACHE_VERSION }}
            mxmd/httpd:${{ env.APACHE_VERSION_MAJOR }}
          build-args: |
            APACHE_VERSION=${{ env.APACHE_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          file: ./Dockerfile

      - name: Generate build timestamp
        id: build-timestamp
        run: echo "BUILD_TIMESTAMP=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            mxmd/httpd:${{ env.APACHE_VERSION }}
            mxmd/httpd:${{ env.APACHE_VERSION_MAJOR }}
            mxmd/httpd:${{ env.APACHE_VERSION }}-${{ env.BUILD_TIMESTAMP }}
            mxmd/httpd:${{ env.APACHE_VERSION_MAJOR }}-${{ env.BUILD_TIMESTAMP }}
          build-args: |
            APACHE_VERSION=${{ env.APACHE_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          file: ./Dockerfile
